/** Médias (YouTube) + textes revus avec des repères encyclopédiques. Photos locales issues du dossier Culture. */

export const frAltTracks = {
  soninke: {
    heritage: {
      subtitle: "Mémoire du Wagadou",
      title: "Les Soninkés",
      description:
        "Héritiers des traditions du monde mandingue, les Soninkés de Mauritanie entretiennent des savoirs oraux, des liens de parenté serrés et un attachement aux foyers historiques du Sahel.",
      body: "On les dit aussi Sarakolé dans certains contextes. Ils sont très présents le long de la vallée moyenne et haute du Sénégal (Boghé, Kaédi, Sélibaby, etc.). Ils nourrissent la mémoire du royaume du Wagadou (« Ghana » médiéval) et de sites sahéliens comme Oualata ou le complexe archéologique de Dhar Tichitt. Les sources ouvertes citent souvent un ordre de grandeur d'environ 200 à 250 000 personnes en Mauritanie — chiffre à croiser avec les recensements officiels. L'arabe, le poular, le soninké et le wolof sont les quatre langues nationales reconnues dans le pays.",
      heroImage: "/soninke-mahdara.jpeg",
      heroImageCaption: "Mahdara soninké — transmission du savoir coranique avec les lawḥ (tablettes en bois).",
      videoId: "2MvBqo6m7MM",
      videoCaption: "Un griot raconte l'histoire soninké — le royaume du Wagadou d'Afrique de l'Ouest — mémoire, généalogies et musique.",
      stats: [
        { value: "~238k", label: "Ordre (sources ouvertes)" },
        { value: "Sénégal", label: "Vallée du fleuve" },
        { value: "4", label: "Langues nationales (MR)" },
      ],
      features: [
        { title: "Gewel & histoire", desc: "Les griots mandingues (gewel / jeli) portent généalogies, épopées et leçons morales ; l'école juridique malékite est majoritaire." },
        { title: "Société lignagère", desc: "Clans (horro / namaxala), alliances matrimoniales et solidarités du quartier structurent la vie collective." },
        { title: "Sahel & carrefours", desc: "Échanges entre savane, fleuve et désert ; patrimoine bâti (Oualata, Dhar Tichitt) rappelle l'ancienneté des réseaux caravaniers." },
        { title: "Fêtes & baptêmes", desc: "Cérémonies familiales rythment le calendrier, mêlant prière, musique mandingue et partage de repas." },
      ],
    },
    music: {
      subtitle: "Rythmes mandingues",
      title: "Musique & poésie soninké",
      description:
        "Répertoires vocaux et percussions hérités du monde mandingue : louanges, satires douces et danses de cercle lors des grandes occasions.",
      artistsTitle: "Voix, tambours & transmission",
      trackLabel: "Piste",
      videos: [
        { id: "Wv6t8SDKwOk", caption: "Bandiougou Kourça Konaté — Gamberé (musique traditionnelle soninké)." },
        { id: "OqtCI6DsF5M", caption: "Compilation de musiques soninké — extraits." },
        { id: "_njlymRyiHU", caption: "Les griots : gardiens de la parole et du répertoire." },
      ],
      artists: [
        { name: "Chants de louange", role: "Répertoire", desc: "Textes mémorisés célébrant ancêtres, hôtes et dignitaires, souvent en appel-réponse." },
        { name: "Ensembles de fête", role: "Percussions", desc: "Tambours et calebasses rythment les sorties nocturnes et les cérémonies de nom." },
        { name: "Transmission orale", role: "Apprentissage", desc: "Les apprentis apprennent à l'oreille, en famille ou au sein des guildes de musiciens." },
      ],
    },
    crafts: {
      subtitle: "Objets & savoir-faire",
      title: "Artisanat & symboles",
      description:
        "Sculpture sur bois, teinture à l'indigo, outils du quotidien et tenues d'apparat : le portail Soninkara recense ces savoir-faire et en rappelle l'ancienneté.",
      videoCaption1: "Instruments et musique — démonstration",
      videoCaption2: "Musique traditionnelle — extraits",
      videoId1: "j-S0crRuRmA",
      videoId2: "CVXifrDdnwQ",
      footerCount: "2 objets & pratiques",
      reference: {
        label: "Portail Soninkara — artisanat soninké",
        url: "http://www.soninkara.org/culture-soninke/artisanat-soninke",
        hint: "rubriques sculpture, teinture, outils traditionnels et tenues.",
      },
      items: [
        { name: "Gambaré (luth soninké)", type: "Cordes", origin: "Sahel / griots", desc: "Luth en calebasse recouvert de peau, instrument noble des griots soninké. Sa caisse allongée produit un son profond accompagnant les épopées du Wagadou.", image: "/soninke-gambare.jpeg" },
        { name: "Outils en fer forgé", type: "Mixte", origin: "Forge / campagne", desc: "Tongué (houe), Pandi (sarcloir), Hidé (cognée), Kado (serpe), Koutiôgadé (foreuse), Tammé (lance), Messellé (aiguille), Labo (couteau) — forgés par les spécialistes tagué.", image: "/soninke-outils-fer.jpeg" },
      ],
    },
    social: {
      subtitle: "Traditions & convivialité",
      title: "Pratiques sociales",
      description:
        "Tam-tam parleur, jeux d'adresse et jeux de stratégie : les pratiques sociales soninké mêlent communication, compétition et solidarité communautaire.",
      howToPlay: "En pratique",
      items: [
        {
          name: "Tam-tam parleur (Fassa)",
          aka: "Communication & convocation",
          image: "/soninke-fassa-drum.jpg",
          description:
            "Tam-tam parleur utilisé pour faire appel aux personnes sur un événement ou un conflit. Dans le temps les Soninkés s'en servaient pour passer une convocation de la part du chef : soit pour une réunion, soit en général quand il y a menace. Ses rythmes codés portent des messages précis à travers les villages.",
          occasion: "Place du village",
          players: "Le griot / le chef",
          rules: [
            "Le griot ou le tambourinaire attitré frappe les rythmes codés sur le grand tam-tam.",
            "Chaque rythme a une signification précise : réunion, alerte, convocation du chef.",
            "Le son porte jusqu'aux villages voisins ; tous reconnaissent le message.",
            "En cas d'urgence ou de menace, un rythme d'alarme spécifique est utilisé.",
          ],
        },
        {
          name: "Garse Tamboullaay",
          aka: "Tirage à la ligne",
          image: "https://images.unsplash.com/photo-1528607929212-2636ec44253e?w=1200&q=80",
          description:
            "Deux camps face à face derrière une ligne ; chaque joueur tire son vis-à-vis ; celui qui franchit la ligne adverse est prisonnier ; chaînes de secours possibles. Valorise la force mesurée et le respect des règles.",
          occasion: "Pleine terre, ligne au sol",
          players: "10–20 par camp",
          rules: [
            "Une ligne médiane (10–20 m) sépare les équipes ; joueurs alignés en vis-à-vis.",
            "Tirades uniquement ; frappes interdites.",
            "Un joueur ramené dans le camp adverse devient prisonnier et sort du jeu.",
            "À la fin, l'équipe avec le plus de prisonniers l'emporte.",
          ],
        },
        {
          name: "Kamr geej (trous dans le sable)",
          aka: "Adresse & course",
          image: "https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?w=1200&q=80",
          description:
            "Trous creusés au sol, chacun portant le nom d'un joueur ; un lanceur envoie une balle depuis 5 m ; si la balle tombe dans un trou, le joueur concerné la récupère et vise les autres qui courent vers un mur-refuge.",
          occasion: "Sable, près d'un mur",
          players: "10–20 enfants ou adolescents",
          rules: [
            "Aligner les trous parallèlement au mur (10–12 m) ; un lanceur à 5 m.",
            "La balle dans un trou désigne le « tireur » ; les autres fuient vers le refuge.",
            "On marque avec des cailloux dans les trous selon les règles de variante choisie.",
            "Adapter le nombre de joueurs et la taille du terrain pour garder le jeu équitable.",
          ],
        },
      ],
    },
  },
  wolof: {
    heritage: {
      subtitle: "Rives & carrefours",
      title: "Les Wolof",
      description:
        "Communauté sénégambienne bien présente le long du fleuve et dans les villes, les Wolof apportent à la Mauritanie un syncrétisme urbain, des modes vestimentaires distincts et une vitalité musicale reconnue.",
      body: "Le wolof est une lingua franca de la Sénégambie : à Nouakchott, Rosso ou le long du fleuve, il colore marchés, radios et fêtes, en dialogue avec l'hassaniya, le français et les autres langues nationales. Les synthèses démographiques évoquent souvent environ 8 % de la population mauritanienne. L'empire du Jolof (XIIIe–XVIe siècle) reste une référence historique ; le soufisme (Tijāniyya, Murīdiyya) marque une partie de la vie religieuse comme au Sénégal.",
      videoId: "quuaGnJ14lQ",
      videoCaption: "Découverte de la culture wolof — Sénégal, Gambie, Mauritanie.",
      stats: [
        { value: "~8%", label: "Population MR (indic.)" },
        { value: "Sénégambie", label: "Aire linguistique" },
        { value: "Jolof", label: "Héritage médiéval" },
      ],
      features: [
        { title: "Tëgg & couture", desc: "Ateliers où se cousent boubous brodés et ensembles festifs pour mariages et Korités." },
        { title: "Daara & éducation", desc: "Réseaux d'enseignement coranique et scolaire côtoyant les traditions de la maisonnée." },
        { title: "Urbain & mobile", desc: "Commerces, transport et médias relient les familles entre Mauritanie et Sénégal." },
        { title: "Solidarité du quartier", desc: "Ndawrabines (associations) financent mariages, deuils et travaux collectifs." },
      ],
    },
    music: {
      subtitle: "Sabar & mbalax",
      title: "Musique wolof",
      description:
        "Tambours sabar, chant lead et danses en cercle : la musique wolof anime les sorties, les télévisions et les fêtes de quartier. Le sabar « parle » — chaque frappe correspond à une syllabe wolof.",
      artistsTitle: "Tambours, voix & danse",
      trackLabel: "Piste",
      videos: [
        { id: "C1AW6S2M9pI", caption: "Danse folklorique sabar — Ballet Jammu, tambours et mouvements." },
        { id: "D9sFBL9RYTM", caption: "Performance sabar à Tivaouane — ensemble Mbengue." },
        { id: "B33pCk2kFmU", caption: "\"Dagen\" — rythme traditionnel de sabar." },
      ],
      artists: [
        { name: "Chœur de tambours", role: "Sabar", desc: "Mbëng-mbëng, nder, lambe : chaque peau a un nom et un rôle ; le ballet des baguettes structure la danse." },
        { name: "Griots & gewel", role: "Parole", desc: "Voix aiguës et vibratos portent les textes satiriques ou élogieux ; généalogistes de mémoire." },
        { name: "Tama & signal", role: "Message", desc: "Le petit tambour sablier « parlant » peut être entendu à 15 km ; lien entre berger et fête." },
      ],
    },
    crafts: {
      subtitle: "Couleurs du fleuve",
      title: "Instruments & modes",
      description:
        "Du luth xalam à la famille sabar en passant par la teinture au wax, les artisans wolof marient savoir-faire sénégalais et touches mauritaniennes.",
      videoCaption1: "Sabar et rythmes — démonstration en Afrique de l'Ouest",
      videoCaption2: "Peinture sous verre de Gorée — art wolof",
      videoId1: "FGYdK5ah5Ns",
      videoId2: "W4tj839-W5A",
      footerCount: "4 instruments & modes",
      items: [
        { name: "Sabar (famille)", type: "Percussion", origin: "Sénégal / MR", desc: "Tambours coniques en bois de dimb, membrane en peau de chèvre. Joués debout avec une main et un galan (baguette en tamarinier)." },
        { name: "Tama (talking drum)", type: "Percussion", origin: "Sénégambie", desc: "Tambour sablier serré sous l'aisselle pour moduler la voix ; 9 frappes correspondent à des énoncés wolof." },
        { name: "Xalam", type: "Cordes", origin: "Griot", desc: "Luth à manche court et peau de varan. Cousin de la tidinit maure et du hoddu peul." },
        { name: "Boubou & broderies", type: "Mixte", origin: "Urbain", desc: "Grand boubou brodé au fil d'argent ou d'or ; teinture wax et bazin pour les cérémonies." },
      ],
    },
    social: {
      subtitle: "Fête & fair-play",
      title: "Jeux & rassemblements",
      description:
        "Compétitions ludiques et veillées musicales créent des ponts entre générations dans les cours et sur les places publiques.",
      howToPlay: "En pratique",
      items: [
        {
          name: "Laamb (lutte sénégalaise)",
          aka: "Sport national",
          image: "https://img.youtube.com/vi/YdtFY7oGAUQ/hqdefault.jpg",
          description: "La lutte traditionnelle wolof permet coups de poing et projections au sol. Avant chaque combat, le lutteur (mbër) exécute un bàkk — performance orale pour intimider l'adversaire — accompagné de tambours sabar et d'amulettes gris-gris.",
          occasion: "Après les récoltes, fêtes nationales",
          players: "2 lutteurs + griots + marabouts",
          rules: [
            "L'objectif est de projeter l'adversaire au sol hors de la zone.",
            "Le bàkk (chant de bravoure) précède chaque combat.",
            "Les marabouts préparent les gris-gris de protection.",
            "Le combat dure entre dix secondes et quatre minutes.",
          ],
        },
        {
          name: "Simb (le faux-lion)",
          aka: "Théâtre de rue",
          image: "https://img.youtube.com/vi/Ne1SqKIHXdY/hqdefault.jpg",
          description: "Spectacle wolof né dans les années 1950 : un performeur grimé en lion (visage rouge, jaune, noir) parcourt les rues en rugissant. Cinq danseurs et deux gaïndé bu djiguène (épouses du lion) animent la scène pendant trois à quatre jours.",
          occasion: "Fête de l'indépendance, festivals de jeunesse",
          players: "5 performeurs + 2 danseuses + tambours",
          rules: [
            "Le faux-lion pourchasse les spectateurs sans billet.",
            "Les tambours jouent le rythme Bakk pour guider la danse.",
            "Les costumes incluent des gris-gris protecteurs.",
            "Le public forme un cercle ; le lion y entre en rugissant.",
          ],
        },
        {
          name: "Yoté (jeu de stratégie)",
          aka: "Plateau à graines",
          image: "https://img.youtube.com/vi/ptUsqtFt9tY/hqdefault.jpg",
          description: "Jeu de plateau wolof vieux de plus de 200 ans, joué sur une grille 5×6 avec 12 pièces par joueur (graines et bois de ndiandiane). Enseigne calcul mental, logique et anticipation à travers les générations.",
          occasion: "Quotidien, sous l'arbre à palabres",
          players: "2 joueurs",
          rules: [
            "Chaque joueur possède 12 pièces à placer ou déplacer.",
            "On capture en sautant par-dessus une pièce adverse.",
            "Après capture, on retire une pièce supplémentaire au choix.",
            "Le gagnant est celui qui capture toutes les pièces adverses.",
          ],
        },
      ],
    },
  },
  pulaar: {
    heritage: {
      subtitle: "Le Pulaaku — Code d'honneur",
      title: "Les Peuls (Fulɓe)",
      description:
        "Plus de 40 millions de Peuls dans 20 pays africains — le plus grand peuple nomade du monde. En Mauritanie, ils cultivent le Pulaaku : patience (munyal), pudeur (semteende), courage (ngorgu) et noblesse d'âme (ndimaagu).",
      body: "Les Peuls (Hal Pulaar) vivent principalement dans les wilayas du Gorgol, Guidimakha, Brakna et Assaba le long du fleuve Sénégal. Le Pulaar est parlé par 70 millions de personnes à travers l'Afrique. Les Peuls mauritaniens ont produit de grands marabouts et érudits islamiques. L'ARPRIM (fondée en 1974) préserve la culture et la langue poular. Le zébu à longues cornes est l'animal totémique — la richesse se compte en têtes de bétail.",
      heroImage: "/pulaar-berger-zebus.jpg",
      heroImageCaption: "Berger peul et ses zébus à longues cornes — le bétail est au cœur de l'identité Fulɓe.",
      videoId: "CEGEDBhrmZg",
      videoCaption: "Mariage traditionnel chez les Peuls du Fouta Toro — traditions d'Afrique de l'Ouest.",
      stats: [
        { value: "40M+", label: "Peuls dans le monde" },
        { value: "70M", label: "Locuteurs du Pulaar" },
        { value: "1974", label: "Fondation ARPRIM" },
      ],
      features: [
        { title: "Pulaaku & valeurs", desc: "Munyal (patience), Semteende (pudeur), Ngorgu (courage), Hakkille (sagesse), Ndimaagu (noblesse d'âme) : le code d'honneur définit l'identité peule." },
        { title: "Transhumance sacrée", desc: "Les Peuls nomades suivent pluies et pâturages. Le wuro (campement) est organisé en cercle autour du bétail, rythme de vie millénaire." },
        { title: "Islam & érudition", desc: "Confréries Tijaniyya et Qadiriyya ; grands marabouts comme El Hadj Oumar Tall du Fouta-Toro, fondateur de l'Empire toucouleur." },
        { title: "Griots & mémoire", desc: "Le griot peul (gewel/bambado) est historien, diplomate, artiste et conseiller — gardien de généalogies sur des centaines d'années." },
      ],
    },
    music: {
      subtitle: "Hoddou & Yéla",
      title: "Musique peule",
      description:
        "Hoddou (luth à 5 cordes), tambin (flûte pastorale), chants yéla et blues peul : une musique qui va de la méditation du berger au festival mondial.",
      artistsTitle: "Voix, hoddou & bergers",
      trackLabel: "Piste",
      videos: [
        { id: "Ag_w58nMGqw", caption: "Gacci — le hoddu, instrument traditionnel de la musique peule." },
        { id: "LUPQ2rxtHtM", caption: "Instruments de la musique Haraka peule — démonstration." },
        { id: "8erCjvbXDqQ", caption: "Alioune B. Sock (guitare) & Cheikh T. Sam (hoddu) — Tono." },
      ],
      artists: [
        { name: "Saidou Bâ", role: "Maître du hoddu", desc: "Né en 1939 au Gorgol, virtuose du hoddu qui a dirigé l'Orchestre National de Mauritanie." },
        { name: "Chants Yéla / Aynabé", role: "Pastoral", desc: "Chants moraux glorifiant les ancêtres et mélodies méditatives des bergers accompagnant le bétail." },
        { name: "Blues peul moderne", role: "Fusion", desc: "Artistes comme Bah Moody fusionnent traditions poular et blues pour une nouvelle génération." },
      ],
    },
    crafts: {
      subtitle: "Art & savoir-faire peul",
      title: "Artisanat nomade",
      description:
        "Poterie gravée, vannerie en rônier, maroquinerie au beurre de karité, calebasses décorées et bijoux en or : un art de vivre mobile où chaque objet est solide et transportable.",
      videoCaption1: "Artisanat peul — poterie et décoration traditionnelle",
      videoCaption2: "Culture Fulɓe — savoir-faire et objets nomades",
      videoId1: "WGHCO4fJn18",
      videoId2: "Njv324LM2jU",
      footerCount: "4 objets nomades",
      items: [
        { name: "Hoddou (luth peul)", type: "Cordes", origin: "Griots peuls", desc: "Luth à 5 cordes en calebasse et peau, instrument noble des griots peuls, équivalent de la tidinit maure. Saidou Bâ en fut le grand maître.", image: "/pulaar-hoddou.jpg" },
        { name: "Poterie décorée", type: "Mixte", origin: "Femmes peules", desc: "Canaris à eau, jarres à lait décorées de motifs géométriques gravés ou peints. Art féminin transmis de mère en fille.", image: "/pulaar-poterie.jpg" },
        { name: "Kwotte (boucles d'or)", type: "Mixte", origin: "Bijouterie", desc: "Grandes boucles d'oreilles en or massif en forme de croissant — emblème de la femme peule mariée. Colliers silki en ambre et corail.", image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400&q=80" },
        { name: "Calebasses laquées", type: "Percussion", origin: "Décoration", desc: "Calebasses gravées et peintes servant de récipients, instruments de musique ou objets décoratifs. Motifs représentant la nature.", image: "https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=400&q=80" },
      ],
    },
    social: {
      subtitle: "Fêtes & cérémonies",
      title: "Vie sociale peule",
      description:
        "Gerewol (festival de beauté masculine), Bantoundé (danse de célébration), joutes d'éloquence : les rassemblements peuls sont des moments forts d'identité collective.",
      howToPlay: "En pratique",
      items: [
        {
          name: "Gerewol (Guérewol)",
          aka: "Festival de beauté masculine",
          image: "/pulaar-gerewol.jpg",
          description: "Cérémonie spectaculaire des Peuls Wodaabé : les hommes se parent de bijoux et de maquillage pour séduire. Danse du regard (Yaake) où les jeunes roulent des yeux et montrent leurs dents blanches. Les femmes choisissent leur partenaire.",
          occasion: "Fin de saison des pluies",
          players: "Jeunes hommes Wodaabé",
          rules: [
            "Les hommes dansent en ligne, maquillés et parés, montant sur la pointe des pieds pour paraître grands.",
            "La danse Yaake dure des heures sous le soleil — les yeux et les dents sont les critères de beauté.",
            "Les femmes observent et choisissent discrètement leur partenaire.",
            "Un breuvage d'écorce fermentée aide à danser pendant les sept jours du festival.",
          ],
        },
        {
          name: "Bantoundé",
          aka: "Danse de célébration",
          image: "/pulaar-femmes-parures.jpg",
          description: "Danse lors des baptêmes, mariages et retours de pèlerinage. Hommes et femmes dansent séparément mais en harmonie, au rythme des tambours et chants polyphoniques.",
          occasion: "Baptêmes, mariages, pèlerinage",
          players: "Toute la communauté",
          rules: [
            "Les femmes dansent en cercle au rythme des tambours ; chaque mouvement a un sens.",
            "Les hommes répondent par leurs propres pas en parallèle.",
            "Le griot anime et chante les louanges des familles.",
            "Bénédiction, fertilité et joie collective guident les mouvements.",
          ],
        },
        {
          name: "Joutes d'éloquence (Jam)",
          aka: "Concours verbal",
          image: "/pulaar-wodaabe.jpg",
          description: "Concours d'improvisation en pulaar sur l'élevage, la foi ou l'actualité. L'élégance du propos prime sur le volume de la voix — art oratoire au cœur du Pulaaku.",
          occasion: "Veillées & fêtes",
          players: "Orateurs de toutes générations",
          rules: [
            "Chaque prétendant dispose du même temps de parole.",
            "Le public juge métaphores, proverbes et courtoisie.",
            "Interrompre est mal vu ; on applaudit à la fin.",
            "Le maître de cérémonie tranche en cas d'égalité.",
          ],
        },
      ],
    },
  },
} as const;

export const arAltTracks = {
  soninke: {
    heritage: {
      subtitle: "ذاكرة واغادو",
      title: "السوننكي",
      description:
        "ورثة تقاليد العالم الماندنغي، يحافظ السوننك في موريتانيا على معارف شفهية وروابط قرابة متينة وتعلق بمواطئ تاريخية في الساحل.",
      body: "يُعرَفون أحياناً بالسراكوليه. يكثر وجودهم في الوسط والجنوب على طول وادي السنغال (بوكي، كيدي، سيليبابي). يحيون ذكرى مملكة واغادو (غانا القديمة) ومواقع مثل ولاتة ودارتيشيت. العربية والبولارية والسوننكية والولوفية أربع لغات وطنية معترف بها.",
      heroImage: "/soninke-mahdara.jpeg",
      heroImageCaption: "محظرة سوننكية — تعليم القرآن على الألواح الخشبية.",
      videoId: "2MvBqo6m7MM",
      videoCaption: "گيويل يروي تاريخ السوننك — مملكة واغادو — الذاكرة والأنساب والموسيقى.",
      stats: [
        { value: "~238 ألف", label: "تقريب (مصادر مفتوحة)" },
        { value: "السنغال", label: "وادي النهر" },
        { value: "٤", label: "لغات وطنية (موريتانيا)" },
      ],
      features: [
        { title: "گيويل وتاريخ", desc: "الگيويل يحملون الأنساب والملاحم؛ المذهب المالكي شائع في غرب أفريقيا المسلم." },
        { title: "مجتمع النسب", desc: "فروع هورو/ناماكالا، تحالفات زوجية وتكافل الحي يهيكلان الحياة الجماعية." },
        { title: "الساحل والملتقى", desc: "تبادلات بين السافانا والنهر والصحراء؛ ولاتة ودارتيشيت تذكّر بقدم الشبكات القوافلية." },
        { title: "الأعياد والختان", desc: "مناسبات عائلية تجمع الصلاة والموسيقى الماندنغية ومشاركة المائدة." },
      ],
    },
    music: {
      subtitle: "إيقاعات ماندنغية",
      title: "موسيقى وشعر سوننكي",
      description: "أغاني ومضارب ورثها العالم الماندنغي: مدائح وهجاء لطيف ورقص دائري في المناسبات الكبرى.",
      artistsTitle: "أصوات وطبول وتلقين",
      trackLabel: "مقطع",
      videos: [
        { id: "Wv6t8SDKwOk", caption: "بانديوگو كورچا كوناتي — گامبيري (موسيقى سوننكية تقليدية)." },
        { id: "OqtCI6DsF5M", caption: "تجميع موسيقى سوننكية — مقاطع." },
        { id: "_njlymRyiHU", caption: "الگيويل: حراس الكلمة والمقامات." },
      ],
      artists: [
        { name: "أغاني المدح", role: "مقام", desc: "نصوص محفوظة تمجّد الأجداد والضيوف، غالباً بصيغة سؤال وجواب." },
        { name: "فرق الحفلات", role: "إيقاع", desc: "طبول وقرعيات لليالي والاحتفالات بمناسبة التسمية." },
        { name: "التلقين الشفهي", role: "تعلّم", desc: "يتعلم المبتدئون بالسماع في البيت أو مع نقابة الموسيقيين." },
      ],
    },
    crafts: {
      subtitle: "أشياء ومهارات",
      title: "الصنعة والرموز",
      description: "نحت خشبي، صبغ بالنيلة، أدوات يومية وأزياء للأعياد: يدوّن موقع سونينكارا هذه الحرف ويربطها بتاريخ الساحل.",
      videoCaption1: "آلات وموسيقى — عرض",
      videoCaption2: "موسيقى تقليدية — مقاطع",
      videoId1: "j-S0crRuRmA",
      videoId2: "CVXifrDdnwQ",
      footerCount: "٢ ممارسات ومقتنيات",
      reference: {
        label: "بوابة سونينكارا — الصنعة السوننكية",
        url: "http://www.soninkara.org/culture-soninke/artisanat-soninke",
        hint: "مقالات النحت والصبغ والأدوات والأزياء.",
      },
      items: [
        { name: "گامباري (عود سوننكي)", type: "Cordes", origin: "الساحل / گيويل", desc: "عود من القرع والجلد، آلة الگيويل السوننكي النبيلة. ينتج صوتاً عميقاً يرافق ملاحم واغادو.", image: "/soninke-gambare.jpeg" },
        { name: "أدوات الحديد المطروق", type: "Mixte", origin: "حدادة / ريف", desc: "تونگي (معول)، باندي (محراث)، هيدي (فأس)، كادو (منجل)، لابو (سكين) — يصنعها حدّادو التاگي.", image: "/soninke-outils-fer.jpeg" },
      ],
    },
    social: {
      subtitle: "تقاليد وألفة",
      title: "ممارسات اجتماعية",
      description: "الطبل الناطق وألعاب المهارة والاستراتيجية: الممارسات الاجتماعية السوننكية تمزج بين التواصل والمنافسة والتكافل.",
      howToPlay: "في الممارسة",
      items: [
        {
          name: "الطبل الناطق (فاسَّا)",
          aka: "تواصل واستدعاء",
          image: "/soninke-fassa-drum.jpg",
          description: "طبل ناطق يُستخدم لاستدعاء الناس لحدث أو نزاع. كان السوننك يستعملونه لتبليغ أوامر الرئيس: اجتماع أو إنذار عند وجود تهديد. إيقاعاته المشفّرة تحمل رسائل واضحة بين القرى.",
          occasion: "ساحة القرية",
          players: "الگيويل / الرئيس",
          rules: [
            "يضرب الگيويل الإيقاعات المشفّرة على الطبل الكبير.",
            "لكل إيقاع معنى دقيق: اجتماع، إنذار، استدعاء من الرئيس.",
            "يصل الصوت إلى القرى المجاورة ويتعرف الجميع على الرسالة.",
            "في حالة تهديد، يُستخدم إيقاع إنذار خاص.",
          ],
        },
        {
          name: "گارس تامبولاي",
          aka: "شدّ على الخط",
          image: "https://images.unsplash.com/photo-1528607929212-2636ec44253e?w=1200&q=80",
          description: "معسكران على خط؛ كل لاعب يشدّ نظيره؛ من يُجرّ إلى جهة الخصم أسير. تُنمّي القوة ضمن قواعد واضحة.",
          occasion: "أرض مسطّحة وخط مرسوم",
          players: "١٠–٢٠ لكل جانب",
          rules: [
            "خط وسط (١٠–٢٠ م) يفصل الفريقين.",
            "الشدّ فقط؛ الضرب ممنوع.",
            "من دخل معسكر الخصم يصبح أسيراً.",
            "الفريق ذو الأسرى الأكثر يفوز.",
          ],
        },
        {
          name: "كامر گيج (حفر في الرمل)",
          aka: "مهارة وركض",
          image: "https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?w=1200&q=80",
          description: "حفر مسمّاة بأسماء اللاعبين؛ يرمي أحدهم كرة من ٥ م؛ إذا سقطت في حفرة لاعب التقطها واستهدف الآخرين الهاربين.",
          occasion: "رمل وجدار أو ملجأ",
          players: "١٠–٢٠ طفلاً أو مراهقاً",
          rules: [
            "صف الحفر موازياً للجدار (١٠–١٢ م)؛ رامٍ على بعد ٥ م.",
            "الكرة في الحفرة تُحدّد المرمي إليهم.",
            "تُسجَّل النقاط بالحصى حسب المتغيّر المتفق عليه.",
            "كيّف عدد اللاعبين لإبقاء اللعب عادلاً.",
          ],
        },
      ],
    },
  },
  wolof: {
    heritage: {
      subtitle: "الساحل والملتقى",
      title: "الولوف",
      description: "جماعة سينيغامبية وازنة على ضفاف النهر وفي المدن، يجلب الولوف إلى موريتانيا مزيجاً حضرياً وأزياء مميزة وحيوية موسيقية.",
      body: "الولوفية لغة تواصل في السينيغامب؛ في نواكشوط وروصو تلون الأسواق والإذاعات والأعياد. تقديرات ديموغرافية تشير إلى نحو ٨٪ من سكان موريتانيا. إمبراطورية جولوف (القرن ١٣–١٦) مرجع تاريخي؛ التصوف (التيجانية والمريدية) يميّز الحياة الدينية.",
      videoId: "quuaGnJ14lQ",
      videoCaption: "اكتشاف ثقافة الولوف — السنغال وغامبيا وموريتانيا.",
      stats: [
        { value: "~٨٪", label: "سكان موريتانيا (تقريب)" },
        { value: "سينيغامب", label: "نطاق لغوي" },
        { value: "جولوف", label: "إرث وسيط" },
      ],
      features: [
        { title: "التيگ والخياطة", desc: "ورش تفصل البوب والأزياء للأعراس والأعياد." },
        { title: "المدارس والتعليم", desc: "شبكات تعليم قرآني ومدرسي بجانب تربية الأسرة." },
        { title: "الحضر والتنقل", desc: "تجارة ومواصلات وإعلام تربط العائلات بين موريتانيا والسنغال." },
        { title: "تكافل الحي", desc: "جمعيات تموّن الأعراس والعزاء والأشغال الجماعية." },
      ],
    },
    music: {
      subtitle: "صابار ومبالاخ",
      title: "موسيقى الولوف",
      description: "طبول صابار وصوت قيادي ورقص دائري: موسيقى الولوف تشعل الأمسيات والحفلات. الصابار «يتكلم» — كل ضربة تقابل مقطعاً ولوفياً.",
      artistsTitle: "طبول وصوت ورقص",
      trackLabel: "مقطع",
      videos: [
        { id: "C1AW6S2M9pI", caption: "رقصة صابار شعبية — فرقة جامو، طبول وحركة." },
        { id: "D9sFBL9RYTM", caption: "عرض صابار في تيفاوان — فرقة مبنگي." },
        { id: "B33pCk2kFmU", caption: "\"داگين\" — إيقاع صابار تقليدي." },
      ],
      artists: [
        { name: "جوق الطبول", role: "صابار", desc: "مبنگ مبنگ، ندر، لامبي: لكل جلد اسم ودور؛ حركة عصي الگالان تهيكل الرقصة." },
        { name: "المغنون الگيويل", role: "كلام", desc: "أصوات عالية وحافظو أنساب يحملون السخرية أو المدح." },
        { name: "التاما والإشارة", role: "رسالة", desc: "الطبل الساعة الرملية «المتكلّم» يُسمع إلى ١٥ كم؛ يربط الراعي بالأفراح." },
      ],
    },
    crafts: {
      subtitle: "ألوان النهر",
      title: "آلات وأزياء",
      description: "من عود الخلم إلى عائلة الصابار وصولاً للتطريز بالواكس، الحرفيون الولوف يمزجون مهارات سنغالية ولمسات موريتانية.",
      videoCaption1: "صابار وإيقاعات — عرض غرب أفريقي",
      videoCaption2: "الرسم تحت الزجاج في غوريه — فن ولوفي",
      videoId1: "FGYdK5ah5Ns",
      videoId2: "W4tj839-W5A",
      footerCount: "٤ آلات وأزياء",
      items: [
        { name: "عائلة الصابار", type: "Percussion", origin: "السنغال / موريتانيا", desc: "طبول مخروطية من خشب الدِّمب وجلد الماعز. يُعزف واقفاً بيد وعصا گالان من التمر الهندي." },
        { name: "تاما (طبل يتكلم)", type: "Percussion", origin: "سينيغامب", desc: "طبل ساعة رملية يُضغط تحت الإبط؛ ٩ ضربات تقابل عبارات ولوفية." },
        { name: "خَلَم", type: "Cordes", origin: "حكواتي", desc: "عود قصير العنق وجلد الورل. قريب من تيدينيت الموريين وهودو الفولاني." },
        { name: "البوب والتطريز", type: "Mixte", origin: "حضر", desc: "بوبو كبير مطرز بخيط الفضة أو الذهب؛ صبغ واكس وبازين للمناسبات." },
      ],
    },
    social: {
      subtitle: "فرح والتزام لطيف",
      title: "ألعاب وتجمعات",
      description: "مسابقات لعب وسهرات موسيقية تبني جسوراً بين الأجيال في الأفنية والساحات.",
      howToPlay: "في الممارسة",
      items: [
        {
          name: "لامب (المصارعة السنغالية)",
          aka: "الرياضة الوطنية",
          image: "https://img.youtube.com/vi/YdtFY7oGAUQ/hqdefault.jpg",
          description: "المصارعة التقليدية الولوفية تسمح باللكمات والطرح أرضاً. قبل كل نزال يؤدي المصارع (مبير) الباكّ — أداء شفاهي لإرهاب الخصم — بمرافقة طبول الصابار وتمائم الگري-گري.",
          occasion: "بعد الحصاد، الأعياد الوطنية",
          players: "٢ مصارعان + گيويل + مرابطون",
          rules: [
            "الهدف طرح الخصم أرضاً خارج المنطقة.",
            "الباكّ (أنشودة الشجاعة) يسبق كل نزال.",
            "المرابطون يعدّون تمائم الحماية.",
            "يدوم النزال بين عشر ثوانٍ وأربع دقائق.",
          ],
        },
        {
          name: "السيمب (الأسد الزائف)",
          aka: "مسرح الشارع",
          image: "https://img.youtube.com/vi/Ne1SqKIHXdY/hqdefault.jpg",
          description: "عرض ولوفي نشأ في الخمسينيات: مؤدٍّ ملوّن الوجه بالأحمر والأصفر والأسود يجوب الشوارع زائراً كالأسد. خمسة راقصين وگايندي بو جيگين (زوجتا الأسد) ينشّطون العرض لثلاثة أو أربعة أيام.",
          occasion: "عيد الاستقلال، مهرجانات الشباب",
          players: "٥ مؤدّين + ٢ راقصتان + طبول",
          rules: [
            "الأسد الزائف يلاحق المتفرجين بلا تذاكر.",
            "الطبول تعزف إيقاع الباكّ لتوجيه الرقص.",
            "الأزياء تتضمن تمائم حماية.",
            "الجمهور يشكّل حلقة ويدخلها الأسد زائراً.",
          ],
        },
        {
          name: "يوتي (لعبة استراتيجية)",
          aka: "لوح البذور",
          image: "https://img.youtube.com/vi/ptUsqtFt9tY/hqdefault.jpg",
          description: "لعبة لوح ولوفية عمرها أكثر من ٢٠٠ عام، تُلعب على شبكة ٥×٦ بـ١٢ قطعة لكل لاعب (بذور وخشب الندياندين). تعلّم الحساب الذهني والمنطق والتوقع عبر الأجيال.",
          occasion: "يومي، تحت شجرة الحوار",
          players: "٢ لاعبان",
          rules: [
            "لكل لاعب ١٢ قطعة يضعها أو يحركها.",
            "الأسر يتم بالقفز فوق قطعة الخصم.",
            "بعد الأسر تُزال قطعة إضافية اختيارية.",
            "الفائز من يأسر جميع قطع الخصم.",
          ],
        },
      ],
    },
  },
  pulaar: {
    heritage: {
      subtitle: "البولاكو — ميثاق الشرف",
      title: "الفولاني (فُلبٜ)",
      description: "أكثر من ٤٠ مليون فولاني في ٢٠ دولة أفريقية — أكبر شعب رحّال في العالم. في موريتانيا يحيون البولاكو: الصبر (مُنيَل)، الحياء (سَمتٜينْدٜ)، الشجاعة (نْگُورْگُ) ونبل النفس (نْدِيمَاگُ).",
      body: "الفولاني (هال بولار) يعيشون في ولايات كوركول وكيديماغا وبراكنا والعصابة على ضفاف نهر السنغال. البولارية يتحدثها ٧٠ مليوناً في أفريقيا. أنتج الفولاني في موريتانيا علماء ومرابطين كباراً. جمعية أربريم (تأسست ١٩٧٤) تحافظ على اللغة والثقافة. الزبو ذو القرون الطويلة حيوان طوطمي — الثروة تُقاس برؤوس الماشية.",
      heroImage: "/pulaar-berger-zebus.jpg",
      heroImageCaption: "راعٍ فولاني وزبوه ذو القرون الطويلة — الماشية في صميم هوية الفُلبٜ.",
      videoId: "CEGEDBhrmZg",
      videoCaption: "زواج تقليدي عند الفولاني في فوتا تورو — تقاليد غرب أفريقيا.",
      stats: [
        { value: "+٤٠ مليون", label: "فولاني في العالم" },
        { value: "٧٠ مليون", label: "ناطقون بالبولارية" },
        { value: "١٩٧٤", label: "تأسيس أربريم" },
      ],
      features: [
        { title: "البولاكو والقيم", desc: "مُنيَل (صبر)، سَمتٜينْدٜ (حياء)، نْگُورْگُ (شجاعة)، حَكّٜيلٜ (حكمة)، نْدِيمَاگُ (نبل): ميثاق الشرف يحدد الهوية الفولانية." },
        { title: "ترحال مقدس", desc: "الرحّل يتتبعون المطر والمرعى. الوُرو (المعسكر) دائري حول الماشية — إيقاع حياة ألفي." },
        { title: "إسلام وعلم", desc: "طريقتا التيجانية والقادرية؛ علماء كبار مثل الحاج عمر تال من فوتا تورو، مؤسس إمبراطورية التكرور." },
        { title: "الگيويل والذاكرة", desc: "الگيويل الفولاني (بمبادو) مؤرخ ودبلوماسي وفنان ومستشار — حافظ أنساب عبر مئات السنين." },
      ],
    },
    music: {
      subtitle: "هودو ويِلَّا",
      title: "موسيقى الفولاني",
      description: "هودو (عود بخمسة أوتار)، تامبين (ناي رعوي)، أغاني يِلَّا وبلوز فولاني: موسيقى تتراوح بين تأمل الراعي والمهرجان العالمي.",
      artistsTitle: "صوت وهودو ورعاة",
      trackLabel: "مقطع",
      videos: [
        { id: "Ag_w58nMGqw", caption: "گاتشي — الهودو، آلة الموسيقى الفولانية التقليدية." },
        { id: "LUPQ2rxtHtM", caption: "آلات موسيقى الهاراكا الفولانية — عرض." },
        { id: "8erCjvbXDqQ", caption: "عليون باداراسوك (گيتار) وشيخ تيبوسام (هودو) — تونو." },
      ],
      artists: [
        { name: "سايدو با", role: "أستاذ الهودو", desc: "وُلد ١٩٣٩ في كوركول، عازف هودو بارع قاد الأوركسترا الوطنية الموريتانية." },
        { name: "أغاني يِلَّا / أيْنَابي", role: "رعوي", desc: "أناشيد أخلاقية تمجد الأجداد وألحان تأمّلية للرعاة مع القطيع." },
        { name: "بلوز فولاني حديث", role: "مزج", desc: "فنانون مثل باه مودي يمزجون التقاليد البولارية بالبلوز لجيل جديد." },
      ],
    },
    crafts: {
      subtitle: "فن ومهارات فولانية",
      title: "صنعة الرحّل",
      description: "فخار محفور، سلال من الرونيي، جلود بزبدة الكاريتي، قرعيات مزخرفة وحُلي ذهبية: عيش متحرك حيث كل شيء متين قابل للنقل.",
      videoCaption1: "صنعة فولانية — فخار وزخرفة تقليدية",
      videoCaption2: "ثقافة فُلبٜ — مهارات وأدوات رحل",
      videoId1: "WGHCO4fJn18",
      videoId2: "Njv324LM2jU",
      footerCount: "٤ أدوات رحل",
      items: [
        { name: "هودو (عود فولاني)", type: "Cordes", origin: "گيويل فولاني", desc: "عود بخمسة أوتار من القرع والجلد، آلة الگيويل النبيلة، نظير تيدينيت الموريين. سايدو با كان أستاذه الكبير.", image: "/pulaar-hoddou.jpg" },
        { name: "فخار مزخرف", type: "Mixte", origin: "نساء فولانيات", desc: "أواني ماء وجرار حليب مزخرفة بأشكال هندسية محفورة أو ملونة. فن نسائي يتوارث.", image: "/pulaar-poterie.jpg" },
        { name: "كوُتّي (أقراط ذهبية)", type: "Mixte", origin: "حُلي", desc: "أقراط هلالية من الذهب الخالص — شعار المرأة الفولانية المتزوجة. قلادات سيلكي من الكهرمان والمرجان.", image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400&q=80" },
        { name: "قرعيات مطلية", type: "Percussion", origin: "زينة", desc: "قرعيات محفورة وملونة تخدم كأوعية وآلات موسيقية وتحف احتفالية.", image: "https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=400&q=80" },
      ],
    },
    social: {
      subtitle: "أعياد وطقوس",
      title: "الحياة الاجتماعية الفولانية",
      description: "الگيريوُل (مهرجان الجمال الذكوري)، البانتوندي (رقصة الاحتفال)، مناظرات البلاغة: تجمعات الفولاني لحظات هوية جماعية.",
      howToPlay: "في الممارسة",
      items: [
        {
          name: "الگيريوُل (Guérewol)",
          aka: "مهرجان جمال الرجال",
          image: "/pulaar-gerewol.jpg",
          description: "طقس مذهل لفولاني وُدابي: الرجال يتزينون بالحلي والمكياج لإغراء النساء. رقصة الياكي حيث يلف الشباب أعينهم ويبرزون أسنانهم البيضاء. النساء يخترن شريكهن.",
          occasion: "نهاية موسم المطر",
          players: "شباب الوُدابي",
          rules: [
            "الرجال يرقصون في صف متزيّنين، يقفون على أطراف أصابعهم ليبدوا طوالاً.",
            "رقصة الياكي تدوم ساعات تحت الشمس — العيون والأسنان معيار الجمال.",
            "النساء يراقبن ويخترن شريكهن بتكتم.",
            "مشروب لحاء مخمّر يساعد على الرقص طوال أيام المهرجان السبعة.",
          ],
        },
        {
          name: "البانتوندي",
          aka: "رقصة الاحتفال",
          image: "/pulaar-femmes-parures.jpg",
          description: "رقصة عند العقيقة والأعراس والعودة من الحج. الرجال والنساء يرقصون منفصلين بتناغم، على إيقاع الطبول والغناء المتعدد الأصوات.",
          occasion: "عقيقة، أعراس، حج",
          players: "كل المجتمع",
          rules: [
            "النساء يرقصن في دائرة على إيقاع الطبول؛ لكل حركة معنى.",
            "الرجال يجيبون بخطواتهم بالتوازي.",
            "الگيويل ينشد ويمدح العائلات.",
            "البركة والخصب والفرح الجماعي تقود الحركات.",
          ],
        },
        {
          name: "مناظرات البلاغة (جام)",
          aka: "مسابقة كلامية",
          image: "/pulaar-wodaabe.jpg",
          description: "مسابقات ارتجال بالبولارية عن الرعي والدين أو الأخبار. أناقة العبارة أهم من علو الصوت — فن الخطابة في صميم البولاكو.",
          occasion: "سهرات وأعياد",
          players: "خطباء من كل الأعمار",
          rules: [
            "لكل متحدث نفس الزمن تقريباً.",
            "الجمهور يقدّر التشبيه والأمثال والأدب.",
            "القطع على الكلام مذموم؛ التصفيق في النهاية.",
            "المسؤول يحكم عند التعادل.",
          ],
        },
      ],
    },
  },
} as const;
